version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'next'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    target-branch: 'next'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      napi:
        patterns:
          - '*napi*'
  - package-ecosystem: 'npm'
    target-branch: 'alpha'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    target-branch: 'alpha'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      napi:
        patterns:
          - '*napi*'
